name: Test Workflow 1

on:
  push:
    branches:
      - main

env:
  TEST_ENV1: test-test1
  TEST_ENV2: test-test2
  TEST_ENV3: test-test3
  TEST_ENV4: test-test4
  TEST_ENV5: test-test5
  TEST_ENV6: test-test6
  TEST_ENV7: test-test7
  TEST_ENV8: test-test8
  TEST_ENV9: test-test9
  TEST_ENV10: test-test10
  TEST_ENV11: test-test11
  TEST_ENV12: test-test12

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, World!"
