name: Update README.md

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README.md
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: ./
          target_branch: main
          commit_message: Update README.md
        env:
          GH_PAT: ${{ secrets.TEST_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5.0.1
        with:
          branch: update-readme
          commit-message: Update README.md
          title: Update README.md
          body: "This pull request updates the README.md file to include new inputs/env variables added to the workflow."
